name: Bug Report / 报告问题
description: Create a report to help us improve. / 报告问题以帮助我们改进
body:
  - type: textarea
    attributes:
      label: Describe the Bug / 描述问题
      description: |
        > A clear and concise description of what the bug is. Please include the device model information (Like xiaomi.gateway.hub1 which can be found in Device info page).
        > 清晰且简明地描述问题。请注明设备 model 信息（例如 xiaomi.gateway.hub1，可在设备详情页查询）。
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce / 复现步骤
      description: |
        > If applicable, add screenshots to help explain your problem. You can attach images by clicking this area to highlight it and then dragging files in. Steps to reproduce the behavior:
        > 如有需要，可添加截图以帮助解释问题。点击此区域以高亮显示并拖动截图文件以上传。请详细描述复现步骤：
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Expected Behavior / 预期结果
      description: |
        > A clear and concise description of what you expected to happen.
        > 描述预期结果。
    validations:
      required: true

  - type: input
    attributes:
      label: Reproduce Time / 问题复现的时间点
      description: |
        > Year-month-day, 24-hour time.
        > 年-月-日，24小时制。
      placeholder: "2025-01-01 17:00:00"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Home Assistant Logs / 系统日志
      description: |
        > Please [set the log level](https://github.com/Hinen-IoT/ha_hinen_power/blob/main/CONTRIBUTING.md#reporting-bugs) to `debug` and try to reproduce the problem.
        > [Settings > System > Logs > DOWNLOAD FULL LOG](https://my.home-assistant.io/redirect/logs) > Filter `hinen_power`
        > 请将[日志级别设置](https://github.com/XiaoMi/ha_hinen_power/blob/main/doc/CONTRIBUTING_zh.md#%E6%88%91%E5%8F%AF%E4%BB%A5%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE)为 `debug` 并尝试复现问题。
        > [设置 > 系统 > 日志 > 下载完整日志](https://my.home-assistant.io/redirect/logs) > 筛选 `hinen_power`

  - type: input
    attributes:
      label: Log Timezone / 日志时区
      description: |
        > The [timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the timestamp in the log.
        > 日志所用时间戳的[时区](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)。
      placeholder: "Asia/Shanghai"
    validations:
      required: true

  - type: input
    attributes:
      label: Home Assistant Core Version / Home Assistant Core 版本
      description: |
        > [Settings > About](https://my.home-assistant.io/redirect/info)
        > [设置 > 关于 Home Assistant](https://my.home-assistant.io/redirect/info)
      placeholder: "2024.11.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Home Assistant Operation System Version / Home Assistant Operation System 版本
      description: |
        > [Settings > About](https://my.home-assistant.io/redirect/info)
        > [设置 > 关于 Home Assistant](https://my.home-assistant.io/redirect/info)
      placeholder: "13.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Hinen Power Integration Version / 米家集成版本
      description: |
        > [Settings > Devices & services > Configured > `Hinen Power`](https://my.home-assistant.io/redirect/integration/?domain=hinen_power)
        > [设置 > 设备与服务 > 已配置 > `Hinen Power`](https://my.home-assistant.io/redirect/integration/?domain=hinen_power)
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context / 其他说明